spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/funTest
    username: postgres
    password: start

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

server:
  port: 8001
